[package]
name = "rsort"
version = "1.0.0"
edition = "2021"
description = "perform different sorting algorithms on lists of numbers"

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
